### ISSUE TITLE
Helm Chart has Incomplete Env Variables

### ISSUE THREAD

**Issue by druidsbane** [newrelic/newrelic-fluent-bit-output#33]
The pods were unable to get host status until I added:
```
- name: HOSTNAME
  valueFrom:
    fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
```

Can we get this added to the Helm chart and the regular deployment file?

More details on a `fluent-bit` issue: https://github.com/fluent/fluent-bit/issues/850#issuecomment-536249449
